networks:
  web:
    external: true

services:
  configserver:
    container_name: configserver
    build: configserver/.
    expose:
      - 8071
    ports:
      - "8071:8071"
    networks:
      - web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  eurekaserver:
    container_name: eurekaserver
    image: "pipe9827/eureka:v1"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    expose:
      - 8070
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - web

  loans:
    container_name: loans
    image: "pipe9827/loans:v1"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    expose:
      - 8090
    ports:
      - "8090:8090"
    depends_on:
      - configserver
      - eurekaserver
    networks:
      - web

  cards:
    container_name: cards
    image: "maikid3v/cards:lab2"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    expose:
      - 9000
    ports:
      - "9000:9000"
    depends_on:
      - configserver
      - eurekaserver
    networks:
      - web

  accounts:
    container_name: accounts
    image: "maikid3v/accounts:lab2"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - configserver
      - eurekaserver
    networks:
      - web

  gatewayserver:
    container_name: gatewayserver
    image: "maikid3v/gateway-server:lab2"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    expose:
      - 8072
    ports:
      - "8072:8072"
    depends_on:
      - configserver
      - eurekaserver
    networks:
      - web
