apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver
  labels:
    app: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      initContainers:
        - name: wait-for-config
          image: curlimages/curl
          command:
            [
              "sh",
              "-c",
              "until curl -f http://configserver:8071/actuator/health; do echo waiting for config server; sleep 2; done",
            ]
      containers:
        - name: eurekaserver
          image: maikid3v/eurekaserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: config-services
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: config-services
                  key: SPRING_CONFIG_IMPORT
