apiVersion: v1
kind: ConfigMap
metadata:
  name: config-services
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_CONFIG_IMPORT: configserver:http://configserver-service:8071/
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver-service:8070/eureka/
