apiVersion: v1
kind: Service
metadata:
  name: gatewayserver-service
spec:
  selector:
    app: gatewayserver
  ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072
  type: LoadBalancer
